### ISSUE TITLE
Zero Byte Images Crash App

### ISSUE THREAD

**Issue by mschwanzer** [zeitdice/zeitmachine-qt#64]
Images like attached do happen on the ZD, nothing we can do about it. ZEITMachine has to prefilter them. Compressed to ZIP because github would not upload ZERO Byte file
[20170815111124.jpg.zip](https://github.com/zeitdice/zeitmachine-qt/files/1262052/20170815111124.jpg.zip)

**Comment by simonrepp** [comment]
I can't reproduce this - zero byte images already get filtered out since a commit in early 2015 (https://github.com/zeitdice/zeitmachine-qt/commit/d5b34ffbd695efb7468949b3d755cccacafb6ea6) and I today confirmed this is working for me on linux and macOS (and as this is using Qt APIs this should be guaranteed to work cross platform anyway).

So I guess we might have jumped to conclusions here and the bug lies elsewhere, can I get an exact report on what you did to trigger the crash without any preliminary interpretation? (possibly make the footage in question available to me as well) :) Thanks!

**Comment by mschwanzer** [comment]
[log_crash.txt](https://github.com/zeitdice/zeitmachine-qt/files/1300011/log_crash.txt)
[Corrupted_File_Timelapse.zip](https://github.com/zeitdice/zeitmachine-qt/files/1300012/Corrupted_File_Timelapse.zip)

You were right about the single zero byte file not being the issue. Here is a sample session with a differently corrupted file and the zero byte file as well, as soon as the folder is loaded, it crashes, report attached as well, no other buttons pressed

**Comment by simonrepp** [comment]
Thanks for the files! :) Ironically the crash orginated precisely in the code that actually removes the 0 byte images ;) - fixed in a6f576f08c5df68b53ce136e8b37fc39c3305583!

**Comment by mschwanzer** [comment]
Again a what looks like a corrupted file issue. Archive includes log.txt (crash report from mac). 
 [20170402_Stopped.zip](https://github.com/zeitdice/zeitmachine-qt/files/1470764/20170402_Stopped.zip)

**Comment by simonrepp** [comment]
Fixed in f80202604981d95ae583e289c7f300714dc3b502 :)
