### ISSUE TITLE
Windows 10 Issues

### ISSUE THREAD

**Issue by mschwanzer** [zeitdice/zeitmachine-qt#67]
User is complaining about Zeitmachine 0.6.1 not starting on Windows 10 Pro, do we have access to a Win 10 Pro machine to replicate issue and get more details how to fix this in the next release 

![](https://downloads.intercomcdn.com/i/o/43155329/017a3537b8a4f20ac676999e/image%5B3%5D.png)

![](https://downloads.intercomcdn.com/i/o/43020354/667aeeed342aaedde60264fe/image%5B3%5D.png)

![](https://downloads.intercomcdn.com/i/o/43020353/8afbdfe25405fd8625d2559f/image%5B1%5D.png)

![](https://downloads.intercomcdn.com/i/o/43020351/911c6d09008ba9d19ce3600e/image%5B1%5D.png)

**Comment by simonrepp** [comment]
I am building and testing on Windows 10 Pro (just checked), no problem there.

I think the issue here is trying to run a 64 bit executable on a 32 bit OS (going by the screenshots), obviously the solution would be (a) using a 64 bit OS instead or (b) we deliver a 32 bit executable as well.

Regarding (b) - I think all libraries (ffmpeg, Qt, Windows runtime) should be readily available to us in 32 bit as well, the challenge here would probably be to gather everything and set things up in a way that doesn't lead to a tedious manual configuration back and forth and version mismatches the next time we build for 64 bit (or both 32 bit and 64 bit) again.

**Comment by mschwanzer** [comment]
sounds reasonable, wont-fix
